version: ""

services:
  mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  backend:
    build:
      context: ./backend
    ports:
      - "5050:5000"

  user_alice:
    build:
      context: ./client
    environment:
      USERNAME: "alice"
      PEERS: "bob,charlie,dave,eve"
      BACKEND: "http://backend:5000"
    depends_on:
      - backend

  user_bob:
    build:
      context: ./client
    environment:
      USERNAME: "bob"
      PEERS: "alice,charlie,dave"
      BACKEND: "http://backend:5000"
    depends_on:
      - backend

  user_charlie:
    build:
      context: ./client
    environment:
      USERNAME: "charlie"
      PEERS: "alice,bob,eve"
      BACKEND: "http://backend:5000"
    depends_on:
      - backend

  user_dave:
    build:
      context: ./client
    environment:
      USERNAME: "dave"
      PEERS: "alice,bob"
      BACKEND: "http://backend:5000"
    depends_on:
      - backend

  user_eve:
    build:
      context: ./client
    environment:
      USERNAME: "eve"
      PEERS: "alice,charlie"
      BACKEND: "http://backend:5000"
    depends_on:
      - backend
